jobs:
  include:
  - language: python
    python: "3.8"
    addons:
      apt_packages:
        - swig
        - python-dev
    cache: pip
    install:
      - pip install -r requirements.txt 
    script: 
      - pytest -v
      - PYTHONPATH=.. sphinx-build -nT -b dummy docs/ docs/_build/html
  - language: python
    python: "3.9"
    addons:
      apt_packages:
        - swig
        - python-dev
    cache: pip
    install:
      - pip install -r requirements.txt 
    script: 
      - pytest -v
      - PYTHONPATH=.. sphinx-build -nT -b dummy docs/ docs/_build/html
  - language: cpp
    compiler: gcc
    script:
      - cd fem/post
      - make 
      - cd create_disp_dat_c
      - make create_disp_dat
      - make test
