name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./fem/post/create_disp_dat_c
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: run test
      run: make test
